### ISSUE TITLE
`'foundationdb/fdb_c.h' file not found` when building in Xcode

### ISSUE THREAD

**Issue by dimitribouniol** [kirilltitov/FDBSwift#56]
I'm trying to play around with FDB in a simple Vapor project, but I'm having trouble getting started. Specifically, when building with Xcode, I get the following errors:
```
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "shim.h"
        ^
/Users/dimitribouniol/Library/Developer/Xcode/DerivedData/hello-bfiigegfzdngdvepisiicspgaxaf/SourcePackages/checkouts/FDBSwift/Sources/CFDB/shim.h:5:14: error: 'foundationdb/fdb_c.h' file not found
    #include "foundationdb/fdb_c.h"
             ^
/Users/dimitribouniol/Library/Developer/Xcode/DerivedData/hello-bfiigegfzdngdvepisiicspgaxaf/SourcePackages/checkouts/FDBSwift/Sources/FDB/FDB.swift:3:8: error: could not build Objective-C module 'CFDB'
import CFDB
       ^
```

This is my Package.swift:
```
// swift-tools-version:5.2
import PackageDescription

let package = Package(
    name: "hello",
    platforms: [
       .macOS(.v10_15)
    ],
    dependencies: [
        // 💧 A server-side Swift web framework.
        .package(url: "https://github.com/vapor/vapor.git", from: "4.0.0-rc"),
        .package(url: "https://github.com/kirilltitov/FDBSwift.git", from: "4.0.0")
    ],
    targets: [
        .target(
            name: "App",
            dependencies: [
                .product(name: "Vapor", package: "vapor"),
                .product(name: "FDB", package: "FDBSwift")
            ],
            swiftSettings: [
                // Enable better optimizations when building in Release configuration. Despite the use of
                // the `.unsafeFlags` construct required by SwiftPM, this flag is recommended for Release
                // builds. See <https://github.com/swift-server/guides#building-for-production> for details.
                .unsafeFlags(["-cross-module-optimization"], .when(configuration: .release))
            ]
        ),
        .target(name: "Run", dependencies: [.target(name: "App")]),
        .testTarget(name: "AppTests", dependencies: [
            .target(name: "App"),
            .product(name: "XCTVapor", package: "vapor"),
        ])
    ]
)
```

Is there something obvious that I'm missing? Things _seem_ to build via `swift build` (the process of which I'm fairly unfamiliar with), but not in Xcode. I did make sure to install the pkgconfig:
<img width="1027" alt="image" src="https://user-images.githubusercontent.com/225505/84067174-e0742100-a97b-11ea-9418-c9d184fe7952.png">

**Comment by kirilltitov** [comment]
Hmm. Let's start with the obvious. Have you installed FoundationDB client? What is the output of `fdbcli --version`? Output of `ls -la /usr/local/include/foundationdb`?

**Comment by dimitribouniol** [comment]
Thanks for the quick reply!

>What is the output of fdbcli --version?
```
% fdbcli --version                     
FoundationDB CLI 6.2 (v6.2.20)
source version 77b5171e81754f2fda8869703d662e59d85b7f23
protocol fdb00b062010001
```

>Output of ls -la /usr/local/include/foundationdb?
```
% ls -la /usr/local/include/foundationdb
total 168
drwxr-xr-x  5 root            wheel    160 Jun  5 17:33 .
drwxrwxr-x  5 dimitribouniol  admin    160 Jun  4 15:24 ..
-rw-r--r--  1 root            wheel  36528 Apr 23 11:22 fdb.options
-rw-r--r--  1 root            wheel  13442 Apr 23 11:22 fdb_c.h
-rw-r--r--  1 root            wheel  31160 Apr 23 11:22 fdb_c_options.g.h
```

**Comment by dimitribouniol** [comment]
My first inclination is that I added it to my project incorrectly (first time messing around with that file 😅) - is anything obvious missing from there?

**Comment by kirilltitov** [comment]
No, there is no funny stuff in terms of usage... Or at least I thought so. Could you please try cloning the repository directly and building/testing it directly? Preferably, the same release you used in your Vapor project (tag `4.0.0`). Try `swift test` it from console, and also Cmd+U from Xcode. I will try the same in the meantime.

**Comment by kirilltitov** [comment]
Also, did you only _build_ your project from console, or did you try running the app?

**Comment by dimitribouniol** [comment]
I only tried building - I wasn't sure nor did I think too much about how to run it from there 😛

Almost all tests pass (except 1) and build in Xcode when I cloned it directly, and checked out `4.0.0`:
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/225505/84070082-67c39380-a980-11ea-9872-f50eadc92471.png">

**Comment by kirilltitov** [comment]
OMG, did they actually change the API in a **PATCH** update, come ooooon... This test is also failing on my machine, but only after I updated the FoundationDB to 6.2.20... Oh well. I will fix the library/test, but I'm not sure it helps you... But let's start from that.

**Comment by dimitribouniol** [comment]
So a simpler package does work fine:
```
// swift-tools-version:5.2
import PackageDescription

let package = Package(
    name: "hello",
    platforms: [
       .macOS(.v10_15)
    ],
    dependencies: [
        .package(url: "https://github.com/kirilltitov/FDBSwift.git", from: "4.0.0")
    ],
    targets: [
        .target(
            name: "App",
            dependencies: [
                .product(name: "FDB", package: "FDBSwift")
            ],
            swiftSettings: [
                // Enable better optimizations when building in Release configuration. Despite the use of
                // the `.unsafeFlags` construct required by SwiftPM, this flag is recommended for Release
                // builds. See <https://github.com/swift-server/guides#building-for-production> for details.
                .unsafeFlags(["-cross-module-optimization"], .when(configuration: .release))
            ]
        ),
        .testTarget(name: "AppTests", dependencies: [
            .target(name: "App"),
        ])
    ]
)
```

**Comment by kirilltitov** [comment]
Hm. That's extremely odd :) Try adding `vapor/vapor` dependency

**Comment by dimitribouniol** [comment]
Alas, adding vapor so it looks exactly like the original package file works fine. The derived data for that package is most likely cursed 😔

Thank you for poking me in the right direction! I look forward to giving these bindings a try!

**Comment by kirilltitov** [comment]
Yeah, when in doubt, rebuild everything from total scratch :) Glad it worked for you! Gonna need to fix that test tho...
