### ISSUE TITLE
Support for version stamps in keys

### ISSUE THREAD

**Issue by dimitribouniol** [kirilltitov/FDBSwift#58]
Is there any interest in adding support for [80-bit](https://github.com/apple/foundationdb/blob/master/design/tuple.md#80-bit-versionstamp) and [96-bit](https://github.com/apple/foundationdb/blob/master/design/tuple.md#96-bit-versionstamp) Versionstamps to Tuple? The `.setVersionstampedKey` option is already there, so all that would need to be done is to add a type code for version stamps, and a check in `Transaction.atomic(_:key:value:)` to look for a single `Versionstamp` type, and append it's position within the key to the end of the key's byte string.

If you are fine with the addition, I'd be more than happy to submit a PR for this, since I've found a need for it.

**Comment by kirilltitov** [comment]
Never hesitate, go for it :) Though I never got the point of it, maybe you could explain it to me? And BTW, from what I see in design doc, 64 and 80 bit typecodes are reserved

**Comment by dimitribouniol** [comment]
I think it's reserved in that it's only fully supported in the Python, JAVA and Go Tuple layer bindings, but it's not like their Swift bindings are actively maintained (honestly, I'm surprised this repo hasn't been integrated as the official one 😅), so I don't see the harm in adding a corresponding implementation here that matches the Python one. I'll add appropriate warnings to the doc comments that this should only be used in apps that exclusively use these bindings, and that should be fine.

The use is to be able to have a unique key in a given transaction without needing to read from the database first to guarantee uniqueness, enabling a faster write with less latency, with no chance for conflict.

**Comment by dimitribouniol** [comment]
I'll take a stab at it today then, thank you!
