### ISSUE TITLE
Transaction `set` is ambiguous.

### ISSUE THREAD

**Issue by jphughes** [kirilltitov/FDBSwift#75]
I am trying transactions using the simple set (no future) from `Sources/FDB/Transaction/Transaction+Sync.swift` line 14 that says 
`    func set(key: AnyFDBKey, value: Bytes, commit: Bool) throws {`
but I am getting an `Ambiguous use of 'set(key:value:commit:)'` because `Sources/FDB/Transaction/Transaction+NIO.swift` line 45 has the same method signature with a different result
`     func set(key: AnyFDBKey, value: Bytes, commit: Bool) -> EventLoopFuture<AnyFDBTransaction> {`

The tests that are in the repository import FDB in as `@testable` and uses internal methods, so they are no help. Any help would be valuable.

**Comment by kirilltitov** [comment]
Try specifying void result type:

```swift
try transaction.set(key: key, value: bytes, commit: shouldCommit) as Void
```

NB: this ambiguity will go away for good in v5 which should land with Swift 6 (or maybe even earlier), when we have concurrency and `async/await`; I will drop SwiftNIO dependency (along with NIO-sibling methods) and all public methods will become async.

**Comment by jphughes** [comment]
Did try that and it threw an error 
`error fdbswift.default : trid=2466853707322889 [FDB.Transaction] [commit] No event loop`

**Comment by kirilltitov** [comment]
Were you using `tr.commit()` method to commit? Because for sync API it's `tr.commitSync()`

**Comment by jphughes** [comment]
OK. That worked. Thanks!

**Comment by kirilltitov** [comment]
Glad I could help! Don't hesitate asking any more questions. And BTW, I wouldn't recommend using blocking sync API, it's not healthy for your app.
