### ISSUE TITLE
Subspace.subspace is internal but readme suggests otherwise. 

### ISSUE THREAD

**Issue by jphughes** [kirilltitov/FDBSwift#76]
The readme and the code are different. Below is code copied from the readme and line 370 gets an error. I am running 4.2.0. 

<img width="1002" alt="image" src="https://user-images.githubusercontent.com/2001484/118726036-99c2b400-b7e5-11eb-8ece-7771b69923e6.png">

**Comment by kirilltitov** [comment]
Well, indeed, it's became internal. Not sure why I did that, but probably there was a reason. Still, it doesn't really limit you — subscripts are available and do absolutely the same.

On the other hand, I couldn't make subscript an anonymous function, and don't know if it's possible at all (like you can do with any other static or dynamic method/func: `let fn: (Int) -> Int = someInstance.func(input:)`), but I doubt that it's your case :)

Will update the readme for now and will reconsider the Subspace API for the next major version.

Thank you!
